language: c
os:
    - osx
    - linux
matrix:
  allow_failures:
    - os: osx
env:
  matrix:
  - CONDA_PY=2.7
addons:
  apt:
    packages:
    - upx-ucl

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CONDA_FLAVOUR='Linux'; else CONDA_FLAVOUR='MacOSX'; fi;
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-${CONDA_FLAVOUR}-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes
    - conda update --yes conda
    - conda install --yes conda-build anaconda-client
    - conda create --yes --name oddt_env python=$CONDA_PY
    # - conda env update --name oddt_env --file environment.yml
    - source activate oddt_env
    - conda install -q six
    - conda install -q -c mwojcikowski openbabel
    - conda install -q -c rdkit rdkit
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda install -q -c conda-forge cairocffi; fi
    # temp
    - conda install -q nomkl numpy scipy scikit-learn joblib
    - conda remove -q mkl
    - pip install --no-deps git+https://github.com/oddt/oddt.git
    - pip install git+https://github.com/pyinstaller/pyinstaller.git
    - pip install git+https://github.com/ajtulloch/sklearn-compiledtrees.git

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./pyinstaller_linux.sh; else ./pyinstaller_macos.sh; fi;
    - ls -lnh dist/

script:
    - dist/oddt_cli --help; exit 0
