sudo: false
language: python
python:
    - '2.7'
addons:
  apt:
    packages:
    - upx-ucl

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes
    - conda update --yes conda
    - conda install --yes conda-build anaconda-client
    - conda create --yes --name oddt_env python=$TRAVIS_PYTHON_VERSION
    # - conda env update --name oddt_env --file environment.yml
    - source activate oddt_env
    - export CONDA_ROOT="$HOME/miniconda/envs/oddt_env/"
    - conda install -q six
    - conda install -q -c mwojcikowski openbabel
    - conda install -q -c rdkit rdkit
    # temp
    - conda install -q numpy scipy scikit-learn joblib
    - pip install --no-deps git+https://github.com/oddt/oddt.git
    - pip install git+https://github.com/pyinstaller/pyinstaller.git
    - pip install git+https://github.com/ajtulloch/sklearn-compiledtrees.git

install:
    - pyinstaller \
        --clean \
        --hidden-import=six \
        --hidden-import=sklearn.tree._utils \
        --hidden-import=compiledtrees \
        --exclude-module tcl \
        --exclude-module Tkinter \
        --add-data '${CONDA_ROOT}/share/openbabel/2.3.90/*:data/' \
        --add-binary '${CONDA_ROOT}/lib/openbabel/2.3.90/*.so:.' \
        --add-binary '${CONDA_ROOT}/lib/libinchi.so.0:.' \
        --add-binary '${CONDA_ROOT}/lib/libmkl_avx.so:.' \
        --add-binary '${CONDA_ROOT}/lib/libmkl_def.so:.' \
        --runtime-hook pyi_rth_obdata.py \
        --add-data=${CONDA_ROOT}/lib/python2.7/site-packages/oddt/scoring/functions/RFScore/*.csv:oddt/scoring/functions/RFScore/ \
        --add-data=${CONDA_ROOT}/lib/python2.7/site-packages/oddt/scoring/functions/NNScore/*.csv:oddt/scoring/functions/NNScore/ \
        --nowindow \
        -n oddt_cli --onefile ${CONDA_ROOT}/bin/oddt_cli`
        --strip \
script:
    - dist/oddt_cli --help
