language: c
os:
    - osx
    - linux
matrix:
  allow_failures:
    - os: osx
env:
  matrix:
  - CONDA_PY=2.7
  - CONDA_PY=3.5
addons:
  apt:
    packages:
    - upx-ucl
deploy:
    provider: bintray/${TRAVIS_OS_NAME}_py${CONDA_PY}.json
    file: bintray/
    user: "mwojcikowski"
    key:
        secure: pP9+5n1YFLuCInQIP2MPwRq3wRd/9gOgndR/KjKo9bhtT3jNKdHvqbjUiyLx0NKS7jZArVsQrtKx0HD7ej5H2NM+WgJeQ7zse05N7P3fNkV8RwfiaVCemP4gh9vdkQCr1GubERMnje2NVMV5Ti0BPX53AOa0zGTHLCV77HIF5hjVf9KbwDzwdXkLaKylVkU9vgBVMrxvA4R//58yFwM/WGtPDuZo/l8oOwx8Qy5rWUjiRMhQwhD+T2q2jHRDcSFXueZ/4VKEx0gwCaxT1xwRl5bG0Qgu7XOLx0Abg9MXB8HCMDfIneyA5vwN8tU9q+WYPzqvD9PCAEBtSHDj5k1CDAikLOz1XFvQy/1HGXqhNuuOK20v6xinj7aY5Z8DKwABRMXsEt7A3iF7YBhRHLVNaGTGviKgtcyPkKUO3zPr58GPYKjI3sgNr5PX+0pYVyi0lHRTJsBO2tV4tf0P7iVnp1oGKbgGbbmHx+DMHKfSJ0+/VT6j7luL5Y7XT9inTTnGTPhoF4zUTfFYdgn5ImfQaEG8vH+8PCGSKfZaR9FQSP4+mXRrFX6vM0zhBlogPi0D0OjTPIyOuVcPajz/cmq54GsXcT8yjXJE/dINd/S5g+tyoWK+qkE6o6L+F+cKcX3XPWbm2zUxRyr9gDof+q84LfQd/BAPyZKRDj7L8O1u+cA=

before_install:
    - ulimit -n 2048
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CONDA_FLAVOUR='Linux'; else CONDA_FLAVOUR='MacOSX'; fi;
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-${CONDA_FLAVOUR}-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes
    - conda update --yes conda
    - conda install --yes conda-build anaconda-client
    - conda create --yes --name oddt_env python=$CONDA_PY
    # - conda env update --name oddt_env --file environment.yml
    - source activate oddt_env
    - conda install -q six
    - conda install -q -c openbabel openbabel
    - conda install -q -c rdkit rdkit
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install upx; fi
    # temp
    - conda install -q numpy scipy scikit-learn joblib
    # - conda remove -q mkl
    - pip install --no-deps git+https://github.com/oddt/oddt.git
    - pip install git+https://github.com/pyinstaller/pyinstaller.git@feb0d271263ca884b91033fd588b79fadf3a3a7f
    # Remove buggy numpy hook instead of @feb0d271263ca884b91033fd588b79fadf3a3a7f
    #- rm -f ${CONDA_PREFIX}/lib/python${CONDA_PY}/site-packages/PyInstaller/hooks/hook-numpy.core.py
    - pip install git+https://github.com/ajtulloch/sklearn-compiledtrees.git

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./pyinstaller_linux.sh; else ./pyinstaller_macos.sh; fi;
    - ls -lh dist/
    - source deactivate

script:
    - dist/oddt_cli --help
    - dist/oddt_cli --toolkit ob test/test_10.mol2 -osmi
    - dist/oddt_cli --toolkit rdk test/test_10.mol2 -osmi
    - time dist/oddt_cli --score rfscore --receptor test/test_10.mol2 test/test_10.mol2 -ocsv

# after_script:
#     - zip -r oddt_cli_${TRAVIS_OS_NAME}_${CONDA_PY}.zip dist/oddt_cli
