language: c
os:
    - osx
    - linux
matrix:
  allow_failures:
    - os: osx
env:
  matrix:
  - CONDA_PY=2.7
  - CONDA_PY=3.5
  global:
  - secure: "vYHrNvBWRdmOO4H+2EuyYf9F3gG/tDups/1yiPvZ5hheAGRoYn++/8pdjSDY4TmosOjygzxfyKVw6IGXZYi2I/MvXKyraaF7xrHgxUYOP7NLeVfrRVQfnGcWmnVIWR23sPPge/ShwpwlvWlVBRlGes/M9Qkubmf8Ybn1al0thHi+Mnpjr5njXLw2CnqYxcWGzsv7wB3vfPoujGa+M61KE5w6lANAChME5qUmYyJByaoUNOYLs6avwu6VzX5EdIU3DUEMadIoTPg1GM5R/YecyNGwBxuhlN/h/oCUpX62hXJzK9+vJPTqujms+5GaI18F8Ln9bQrBlIvMIqYuyhN5qrUlFnVlYpBYtbMnXNgG285hsV1OzNTLRuk9zfA6mYm7GVRkdjj7Ht201BHT0289JTDSHQ+UdYzGRzMYRpBzC1pUSK8KRPpOtIxD6Zi2fciJuM7vr20qdPmN//PULZ+8iZdomkxUqSUXN2UWbhZITVTAWG2npOnIPLysBelTrG5nsx5qpjmQNJ6N+HPR97oxJttqGp5v2X8bTRTOH4g1ddmia1aWrU1nFuKNL7UmQxdJpnAnMF2qybu16iFJtyAMhcK1qEQ/OUg8EEz3g1AjB23SVDNxKdXtuRToHXDIaEPApC7mJuXKbGxhxjRjs0pfz7+GndHzStAqR7z+S9LCB/c="
  - secure: "2ms3MiNHHKJQ5QV6TqWxPLi8rxnnuxXQOTLJkcS+VL1qvJxhpEXH5iiAcrRVHpZrFxDf4WVYumX6yU2yhCrxD8MefqNRO0ihW162qpp74OBAWed7hOzaBx+2ssgt2Kz2hifjDyUhEAAeggOGribixjUosdKTC2xcVHN59ZIMuSbx82aWcUadqYZlFQUub0hDKokAbJ2ZRK/h6ssHsZ1bOeyn7el7UaW3V2JPY4FhnUjk6KoOMMdATD6E9xMpuvkX8F3KnyAzpqg+tqifrN7mgdtNq7JTI4dRJwONhNZWAAeIV+adN3r+ACuD6Yniy0X2fXb9BZj0YPTrJXQL1nu0tAGUuMdTf48AXwmpnQqVyEY2ZcqoYX1VfYsRW8zT0K+/0tawH/dySBPMWcMyiYht+dTaT5BLnAo8xADCn3p5kUSveCBW8E2XJYhTZtBcUg3S5ivpCwRK8A4ofFmjU58NlSM1vHRenVZN8yuiAawxxfMFt2+4u3DyKwR6N7MhAqWY2VTTa5mI6LacYUwqxudiuhxIWdYBaxDBtOv8p3uX1YYY1i/OVGtPD9aGxGV2/do/M8LTOd2TCakcVsmOg6UN1J9FW7Z9MPBANFXI3jeOv5kSSxhJKRlYqtPPjSZ1/7Pt3DzxoKYaM6nzc3zFt2ApvbGOpLnFs5+Yvau0Kz3V16g="
addons:
  apt:
    packages:
    - upx-ucl

before_install:
    - ulimit -n 2048
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CONDA_FLAVOUR='Linux'; else CONDA_FLAVOUR='MacOSX'; fi;
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-${CONDA_FLAVOUR}-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes
    - conda update --yes conda
    - conda install --yes conda-build anaconda-client
    - conda create --yes --name oddt_env python=$CONDA_PY
    # - conda env update --name oddt_env --file environment.yml
    - source activate oddt_env
    - conda install -q six
    - conda install -q -c openbabel openbabel
    - conda install -q -c rdkit rdkit
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install upx; fi
    # temp
    - conda install -q numpy scipy scikit-learn joblib
    # - conda remove -q mkl
    - pip install --no-deps git+https://github.com/oddt/oddt.git
    - export ODDT_VER=`python -c "from __future__ import print_function; import oddt; print(oddt.__version__)"`
    - pip install git+https://github.com/pyinstaller/pyinstaller.git@feb0d271263ca884b91033fd588b79fadf3a3a7f
    # Remove buggy numpy hook instead of @feb0d271263ca884b91033fd588b79fadf3a3a7f
    #- rm -f ${CONDA_PREFIX}/lib/python${CONDA_PY}/site-packages/PyInstaller/hooks/hook-numpy.core.py
    - pip install git+https://github.com/ajtulloch/sklearn-compiledtrees.git

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./pyinstaller_linux.sh; else ./pyinstaller_macos.sh; fi;
    - ls -lh dist/
    - source deactivate

script:
    - dist/oddt_cli --help
    - dist/oddt_cli --toolkit ob test/test_10.mol2 -osmi
    - dist/oddt_cli --toolkit rdk test/test_10.mol2 -osmi
    - time dist/oddt_cli --score rfscore --receptor test/test_10.mol2 test/test_10.mol2 -ocsv

after_success:
    - zip -r oddt_cli_v${ODDT_VER}_${TRAVIS_OS_NAME}_${CONDA_PY}.zip dist/oddt_cli
    - "curl --ftp-create-dirs -T oddt_cli_v${ODDT_VER}_${TRAVIS_OS_NAME}_${CONDA_PY}.zip -u $FTP_USER:$FTP_PASSWORD ftp://wojcikowski.pl"
