environment:
  # See README for information on the token
  ANACONDA_TOKEN:
    secure: AaDohlZ5kwkG4ymSAkUVvTIzL1SDr1WMl/0A/07mnOWqcxOTDMqaMTSeDSvlOEZV
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"

    #- PYTHON: "C:\\Python34_32"
    #  PYTHON_VERSION: "3.4"
    #  PYTHON_ARCH: "32"
    #  CONDA_PY: "34"

    # - PYTHON: "C:\\Python34_64"
    #   PYTHON_VERSION: "3.4"
    #   PYTHON_ARCH: "64"
    #   CONDA_PY: "34"

    #- PYTHON: "C:\\Python35_32"
    #  PYTHON_VERSION: "3.5"
    #  PYTHON_ARCH: "32"
    #  CONDA_PY: "35"

    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"

install:
    # https://www.appveyor.com/docs/installed-software#python
    - if "%PYTHON_VERSION%" == "3.4" set "BASE_PYTHON_VERSION=3"
    - if "%PYTHON_VERSION%" == "3.5" set "BASE_PYTHON_VERSION=35"
    - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
    # These are already installed on appveyor.  Update them.
    - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
    - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
    - conda config --set always_yes yes
    - conda update -q conda
    - conda info
    - conda update -q --all
    - python -c "import sys; print(sys.version)"
    - python -c "import sys; print(sys.executable)"
    - python -c "import sys; print(sys.prefix)"
    - conda create --yes --name oddt_env python=%PYTHON_VERSION%
    - activate oddt_env
    - conda install -q six
    - conda install -q -c conda-forge mingwpy
    - conda install -q -c mwojcikowski openbabel
    - conda install -q -c rdkit rdkit
    # temp
    - conda install -q numpy scipy scikit-learn joblib
    - pip install --no-deps git+https://github.com/oddt/oddt.git@experimental-windows
    # Use commit pre-MKL
    - pip install git+https://github.com/pyinstaller/pyinstaller.git
    # Remove buggy numpy hook instead of @feb0d271263ca884b91033fd588b79fadf3a3a7f
    - python -c "import PyInstaller;print(PyInstaller.__file__)"
    - del /F %CONDA_PREFIX%\Lib\site-packages\PyInstaller\hooks\hook-numpy.core.py
    # compiledtrees
    #- pip install --global-option --compiler=mingw git+https://github.com/ajtulloch/sklearn-compiledtrees.git
    - git clone https://github.com/ajtulloch/sklearn-compiledtrees.git
    - cd sklearn-compiledtrees
    - python setup.py build_ext --compiler=mingw --inplace
    - python setup.py install
    - curl -L -o upx.zip http://libgd.blob.core.windows.net/upx/upx391w.zip && 7z e upx.zip *.exe -r


build: false

test_script:
  - 'pyinstaller --clean ^
        --additional-hooks-dir . ^
        --hidden-import="sklearn.tree._utils" ^
        --hidden-import=six ^
        --hidden-import=compiledtrees ^
        --hidden-import=rdkit ^
        --runtime-hook pyi_rth_obdata.py ^
        --runtime-hook pyi_rth_rdkit.py ^
        --add-binary "%CONDA_PREFIX%\Library\bin\mkl_avx.dll;." ^
        --add-binary "%CONDA_PREFIX%\Library\bin\formats_*.obf;." ^
        --add-binary "%CONDA_PREFIX%\Library\bin\plugin_*.obf;." ^
        --add-data "%CONDA_PREFIX%\share\openbabel\*;data" ^
        --add-data "%CONDA_PREFIX%\Library\share\RDKit\Data\*;rdkit\Data" ^
        --add-data "%CONDA_PREFIX%\Lib\site-packages\oddt\scoring\functions\RFScore\*.csv;oddt\scoring\functions\RFScore" ^
        --exclude-module tcl ^
        --exclude-module Tkinter ^
        --noupx ^
        --nowindow ^
        -y -n oddt_cli --onefile %CONDA_PREFIX%\Scripts\oddt_cli'
  - deactivate
  - dist\oddt_cli.exe --help
  - dist\oddt_cli.exe --toolkit ob test\test_10.mol2 -osmi
  - dist\oddt_cli.exe --toolkit rdk test\test_10.mol2 -osmi
  - dist\oddt_cli.exe --score rfscore --receptor test\test_10.mol2 test\test_10.mol2 -ocsv
artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: .\dist\oddt_cli.exe
